/* GENERATED by tools/quiz-data.mjs — do not edit. Re-run after editing lesson quizzes. */
window.QUIZ = {
 "m1": [
  {
   "q": "Two developers use the identical AI model; one gets reliable code, one gets a mess. What best explains the difference?",
   "opts": [
    "One paid for a bigger model tier",
    "The system each built around the model",
    "One wrote much longer prompts"
   ],
   "a": 1,
   "why": "Same model, different result — the difference is the system of planning, context, and validation around it.",
   "lesson": "01-why-a-system",
   "n": 1,
   "title": "Why AI Coding Needs a System"
  },
  {
   "q": "If AI “amplifies whatever you already have,” what happens when you add it to a chaotic process?",
   "opts": [
    "The chaos gets cleaned up",
    "Nothing changes at all",
    "You get more chaos, faster"
   ],
   "a": 2,
   "why": "AI amplifies your existing process — good or bad. No system means the mess just scales up faster.",
   "lesson": "01-why-a-system",
   "n": 1,
   "title": "Why AI Coding Needs a System"
  },
  {
   "q": "A developer lets the agent write every line of code but insists on defining the goal upfront and checking the result before shipping. Are they vibe coding?",
   "opts": [
    "Yes — if the agent typed it, it's vibe coding",
    "No — they still own the planning and the validation",
    "Only if the code is short"
   ],
   "a": 1,
   "why": "Driver's seat is about who owns the intent, the approach, and the proof — not about who types the code. You can delegate 100% of the keystrokes and still be fully in control.",
   "lesson": "02-driver-or-passenger",
   "n": 2,
   "title": "Driver's Seat vs. Passenger"
  },
  {
   "q": "What's the biggest risk of vibe coding a feature that real users will depend on?",
   "opts": [
    "It takes too many keystrokes",
    "The agent will refuse the request",
    "The agent fills in unstated assumptions, producing code that looks fine but is quietly wrong"
   ],
   "a": 2,
   "why": "Vibe coding removes upfront planning and real validation, which is fine for disposable work but risky the moment code needs to last or handle anything real.",
   "lesson": "02-driver-or-passenger",
   "n": 2,
   "title": "Driver's Seat vs. Passenger"
  },
  {
   "q": "Which loop should take up most of your time as an agentic coder?",
   "opts": [
    "The inner loop",
    "The outer loop",
    "Both equally, on a fixed schedule"
   ],
   "a": 0,
   "why": "You live in the inner loop for the overwhelming majority of your work — it's the loop that actually ships things. The outer loop is a rare, deliberate step out.",
   "lesson": "03-the-two-loops",
   "n": 3,
   "title": "The Two Loops"
  },
  {
   "q": "Back in Lesson 1 we said the real bottleneck is the system around the model, not the model itself. Which loop is specifically about closing that kind of gap when it shows up repeatedly?",
   "opts": [
    "The inner loop, by running Validate more carefully",
    "The outer loop, by adjusting the system so the recurring mistake is less likely",
    "Neither — you'd just switch to a different agent"
   ],
   "a": 1,
   "why": "Lesson 1's system gap is exactly what the outer loop closes: when the same mistake recurs, you step out and fix the system around the agent instead of the model itself.",
   "lesson": "03-the-two-loops",
   "n": 3,
   "title": "The Two Loops"
  },
  {
   "q": "In the four-step core loop, which single step is the one you delegate entirely to the agent?",
   "opts": [
    "Research",
    "Plan",
    "Implement"
   ],
   "a": 2,
   "why": "Implement is the one step you fully hand to the agent. Research and Plan are your thinking beforehand; Validate is your checking afterward — the sandwich from the driver's-seat lesson.",
   "lesson": "03-the-two-loops",
   "n": 3,
   "title": "The Two Loops"
  },
  {
   "q": "You're dropped into a two-year-old codebase with no design docs. What's your first job before writing any code?",
   "opts": [
    "Write a brand-new founding document from scratch, ignoring the code",
    "Read the existing code and structure to uncover its intent and conventions",
    "Skip straight to Implement since the project already exists"
   ],
   "a": 1,
   "why": "Brownfield has no founding document to read from — the existing code itself carries the intent and conventions, so your first job is to read them out rather than write them down.",
   "lesson": "04-three-ways-in",
   "n": 4,
   "title": "Three Ways In"
  },
  {
   "q": "A greenfield idea, a brownfield project, and a single bug fix all eventually feed into what?",
   "opts": [
    "The same core loop — Research, Plan, Implement, Validate",
    "Three completely separate workflows you must learn independently",
    "Only the bug fix uses a loop; the other two don't need one"
   ],
   "a": 0,
   "why": "All three doorways feed the exact same core loop — Research, Plan, Implement, Validate. Only how you get oriented at the door differs.",
   "lesson": "04-three-ways-in",
   "n": 4,
   "title": "Three Ways In"
  }
 ],
 "m2": [
  {
   "q": "In the three-layer stack, where does the context layer sit?",
   "opts": [
    "It's the coding agent itself",
    "Between the agent you pick and the plan you produce for one task",
    "It only exists after the project ships"
   ],
   "a": 1,
   "why": "The agent is the base you pick, the context layer is what you build on top of it, and the per-task plan is produced fresh inside a single work session.",
   "lesson": "05-the-context-layer",
   "n": 5,
   "title": "The Context Layer"
  },
  {
   "q": "What's the risk of treating the context layer like a rigid framework you install once?",
   "opts": [
    "It becomes too easy to maintain",
    "The agent ignores it entirely",
    "It stops fitting your project and becomes a burden instead of a help"
   ],
   "a": 2,
   "why": "A context layer that tries to anticipate everything up front becomes its own burden. Start small, keep it true, and grow it as reality demands.",
   "lesson": "05-the-context-layer",
   "n": 5,
   "title": "The Context Layer"
  },
  {
   "q": "Of the six building blocks, which is usually the most codebase-specific and highest-value to set up first?",
   "opts": [
    "Rules",
    "Hooks",
    "Code search / navigation"
   ],
   "a": 0,
   "why": "Rules encode your codebase's own conventions and constraints, so they're the most specific and highest-value piece to get right first.",
   "lesson": "06-six-building-blocks",
   "n": 6,
   "title": "The Six Building Blocks"
  },
  {
   "q": "You keep re-explaining the same multi-step process to your agent every week. Which building block solves that?",
   "opts": [
    "A hook",
    "A skill",
    "Code search / navigation"
   ],
   "a": 1,
   "why": "A skill packages a workflow so you name it once and reuse it, instead of re-explaining the same multi-step process every time.",
   "lesson": "06-six-building-blocks",
   "n": 6,
   "title": "The Six Building Blocks"
  },
  {
   "q": "Why hand a big research task to a subagent instead of doing it in your main conversation?",
   "opts": [
    "Subagents are the only block that can read files",
    "It automatically fixes bugs it finds",
    "It keeps that heavy digging in its own context, out of your way"
   ],
   "a": 2,
   "why": "Subagents run with their own separate context, so heavy research or review work doesn't clutter your main conversation.",
   "lesson": "06-six-building-blocks",
   "n": 6,
   "title": "The Six Building Blocks"
  },
  {
   "q": "Why doesn't stuffing every possible detail into the always-loaded rules file make the agent smarter?",
   "opts": [
    "The agent can't read long files at all",
    "It competes for limited attention and buries what's actually relevant",
    "Long files cost extra to store"
   ],
   "a": 1,
   "why": "Context is a scarce resource — piling everything into the always-loaded tier buries the relevant details and degrades the agent's judgment.",
   "lesson": "07-progressive-disclosure",
   "n": 7,
   "title": "Progressive Disclosure"
  },
  {
   "q": "What does a skill show the agent before it's ever invoked?",
   "opts": [
    "Just its name and a short description",
    "The entire step-by-step workflow",
    "Nothing — skills are invisible until run"
   ],
   "a": 0,
   "why": "A skill's name and description are the always-loaded tier — enough for the agent to recognize relevance. The full instructions are on-demand, read only once invoked.",
   "lesson": "07-progressive-disclosure",
   "n": 7,
   "title": "Progressive Disclosure"
  },
  {
   "q": "The agent makes the exact same kind of mistake for the third time this month. What should that trigger?",
   "opts": [
    "Nothing — just fix this instance and move on like always",
    "Switching to a different coding agent entirely",
    "Stepping out to update your context layer, usually a rule, so that class of mistake gets rarer"
   ],
   "a": 2,
   "why": "A recurring mistake is a system signal, not just a bug — it means something in the context layer should change so the whole class of failure gets rarer.",
   "lesson": "08-evolving-the-system",
   "n": 8,
   "title": "Evolving the System"
  },
  {
   "q": "Why doesn't just hand-fixing each recurrence of a mistake make things better over time?",
   "opts": [
    "Because the underlying cause is never addressed, so it just happens again",
    "Because hand-fixing is technically impossible",
    "Because agents remember every past correction automatically"
   ],
   "a": 0,
   "why": "Hand-fixing only corrects today's instance; the underlying cause stays in place and the same mistake recurs next time. Folding the lesson into the context layer is what moves the baseline.",
   "lesson": "08-evolving-the-system",
   "n": 8,
   "title": "Evolving the System"
  },
  {
   "q": "Recalling the two loops from earlier in the course: which loop is \"evolving the system\" an example of?",
   "opts": [
    "The inner loop — it happens every single task",
    "The outer loop — you step out of building to improve the system, then step back in",
    "There's only one loop; this course doesn't distinguish them"
   ],
   "a": 1,
   "why": "The inner loop (the day-to-day build-and-check rhythm) is where most time is spent; the outer loop is the occasional step-out to improve the system itself. Evolving the system is the outer loop in action.",
   "lesson": "08-evolving-the-system",
   "n": 8,
   "title": "Evolving the System"
  }
 ],
 "m3": [
  {
   "q": "What's the biggest mistake you can make when applying the core loop?",
   "opts": [
    "Skipping the research step on a simple task",
    "Handing the agent an entire project or feature at once",
    "Writing the plan before starting the conversation"
   ],
   "a": 1,
   "why": "Small, granular scope is the rule that makes the rest of the loop work. A whole project overwhelms the agent and produces the worst results.",
   "lesson": "09-the-core-loop",
   "n": 9,
   "title": "The Core Loop"
  },
  {
   "q": "What are the four steps of the core loop, in order?",
   "opts": [
    "Research, Plan, Implement, Validate",
    "Plan, Research, Validate, Implement",
    "Implement, Validate, Plan, Research"
   ],
   "a": 0,
   "why": "Research, Plan, Implement, Validate — in that order, repeated per task.",
   "lesson": "09-the-core-loop",
   "n": 9,
   "title": "The Core Loop"
  },
  {
   "q": "Why does this course call the four-step rhythm \"the most stable idea\" in the whole system?",
   "opts": [
    "Because it only works with one specific coding agent",
    "Because it was the first thing ever written about AI coding",
    "Because it holds steady across different tools, models, and project sizes"
   ],
   "a": 2,
   "why": "The core loop is deliberately the most stable, least-changed idea in the course — it's designed to outlast any specific tool or model.",
   "lesson": "09-the-core-loop",
   "n": 9,
   "title": "The Core Loop"
  },
  {
   "q": "When should you spend real time and effort on the research step?",
   "opts": [
    "When the task is new, vague, or touches unfamiliar code",
    "Every single time, in exactly the same depth",
    "Only after the implementation has already failed once"
   ],
   "a": 0,
   "why": "Research scales with novelty — skip or lighten it for familiar work, invest real effort for new or vague work.",
   "lesson": "10-research-first",
   "n": 10,
   "title": "Research First"
  },
  {
   "q": "What's the risk of skipping research on a task that genuinely needed it?",
   "opts": [
    "Nothing — research is purely optional overhead",
    "The plan will simply take a little longer to write",
    "You discover the missing understanding mid-implementation, which is costly to fix"
   ],
   "a": 2,
   "why": "Skipping research on a task that actually needed it usually means the missing understanding surfaces mid-implementation, which is the most expensive place to find it.",
   "lesson": "10-research-first",
   "n": 10,
   "title": "Research First"
  },
  {
   "q": "What's the real test for whether a plan is \"one-pass-ready\"?",
   "opts": [
    "Whether it's at least one page long",
    "Whether a fresh agent with no prior context could implement it correctly from the plan alone",
    "Whether the human who wrote it feels confident about it"
   ],
   "a": 1,
   "why": "The bar is whether a fresh agent with zero conversation context could implement it correctly from the document alone — real file paths, explicit scope, and a validation strategy are what get it there.",
   "lesson": "11-the-plan",
   "n": 11,
   "title": "The Plan That Ships in One Pass"
  },
  {
   "q": "Which section of a one-pass-ready plan is worth the most iteration?",
   "opts": [
    "The validation strategy",
    "The title of the document",
    "The list of out-of-scope items"
   ],
   "a": 0,
   "why": "The validation strategy — how the agent will prove its own work — is the single highest-leverage section of the plan.",
   "lesson": "11-the-plan",
   "n": 11,
   "title": "The Plan That Ships in One Pass"
  },
  {
   "q": "What is \"context rot\"?",
   "opts": [
    "A bug that only affects certain coding agents",
    "The hard technical limit where a model stops responding entirely",
    "A model getting measurably worse well before it hits its hard token limit"
   ],
   "a": 2,
   "why": "Context rot describes a model getting measurably worse well before its hard token limit, typically somewhere around 200,000 to 300,000 tokens of accumulated conversation.",
   "lesson": "12-clean-context",
   "n": 12,
   "title": "Clean Context"
  },
  {
   "q": "What makes it safe to clear context and start implementation in a fresh session?",
   "opts": [
    "Having a plan that passes the \"no prior knowledge\" test",
    "Making sure the planning conversation was as long as possible",
    "Keeping the agent's memory turned on between sessions"
   ],
   "a": 0,
   "why": "A comprehensive, one-pass-ready plan is exactly what licenses clearing context — without it, a fresh session has nothing solid to build from.",
   "lesson": "12-clean-context",
   "n": 12,
   "title": "Clean Context"
  },
  {
   "q": "Why are \"does it work\" and \"is it built well\" treated as two separate questions?",
   "opts": [
    "Because only one of them actually matters",
    "Because mixing them produces a shallow answer to both",
    "Because agents can only answer one question per session"
   ],
   "a": 1,
   "why": "Validation ('does it work?') and review ('is it built well?') are deliberately kept separate — mixing them produces a shallow version of both.",
   "lesson": "13-validate-and-gates",
   "n": 13,
   "title": "Validate & Gates"
  }
 ],
 "m4": [
  {
   "q": "Which altitude answers \"what problem are we solving, and for whom\"?",
   "opts": [
    "Task",
    "Intent",
    "Architecture"
   ],
   "a": 1,
   "why": "Intent is the what and why; architecture is the shape of the solution; task is the per-ticket implementation. Each rests on the one above it.",
   "lesson": "14-three-altitudes",
   "n": 14,
   "title": "The Three Altitudes"
  },
  {
   "q": "An agent is asked to \"just build the feature\" with no strategic doc and no architecture decisions in place. What's the risk?",
   "opts": [
    "Nothing — the agent will ask before deciding anything",
    "The task will simply take longer to run",
    "The agent quietly decides the what/why and the how on its own, and you find out only after the code is written"
   ],
   "a": 2,
   "why": "Letting an agent invent the product intent and the architecture while you only asked for a task is the classic altitude mix-up — and it's usually invisible until the code is already wrong.",
   "lesson": "14-three-altitudes",
   "n": 14,
   "title": "The Three Altitudes"
  },
  {
   "q": "What's the right rhythm for planning across a whole epic or feature?",
   "opts": [
    "Plan wide at intent and architecture altitude, then split narrow to implement",
    "Plan narrow for each ticket first, then infer the architecture afterward",
    "Skip planning and let each ticket decide its own architecture"
   ],
   "a": 0,
   "why": "Plan wide across the whole piece of work at the top two altitudes, then split narrow — implementing one small, testable slice at a time.",
   "lesson": "14-three-altitudes",
   "n": 14,
   "title": "The Three Altitudes"
  },
  {
   "q": "Which of these belongs in a strategic doc?",
   "opts": [
    "The database schema and API routes",
    "The problem, the users, and what success looks like",
    "Pseudocode for the first ticket"
   ],
   "a": 1,
   "why": "A strategic doc is intent altitude — the what and the why. The how belongs in a separate architecture document.",
   "lesson": "15-strategic-doc",
   "n": 15,
   "title": "The Strategic Doc"
  },
  {
   "q": "Why does a wrong assumption in the strategic doc matter so much more than a wrong assumption in one ticket?",
   "opts": [
    "It doesn't — a doc is easy to fix later",
    "Because it takes longer to write than a ticket",
    "Because every downstream plan and every ticket inherits it, so the mistake compounds"
   ],
   "a": 2,
   "why": "Every later plan — architecture, tickets, implementation — inherits its assumptions from the strategic doc. A wrong assumption here cascades downstream.",
   "lesson": "15-strategic-doc",
   "n": 15,
   "title": "The Strategic Doc"
  },
  {
   "q": "What turns a feature idea into a falsifiable hypothesis?",
   "opts": [
    "Writing it down in a formal-sounding document",
    "Getting a manager to approve it",
    "Stating the expected outcome plus the measurable condition that would prove it wrong"
   ],
   "a": 2,
   "why": "A falsifiable hypothesis names both the expected outcome and the condition that would prove it wrong. Without the wrong-condition, it's just a hope.",
   "lesson": "16-falsifiable-hypothesis",
   "n": 16,
   "title": "The Falsifiable Hypothesis"
  },
  {
   "q": "Which of these is NOT falsifiable?",
   "opts": [
    "\"This will improve the user experience.\"",
    "\"We believe this will cut checkout time below 90 seconds for 70% of sessions, or we were wrong.\"",
    "\"We believe this will raise week-two retention above 40%, or we were wrong.\""
   ],
   "a": 0,
   "why": "\\",
   "lesson": "16-falsifiable-hypothesis",
   "n": 16,
   "title": "The Falsifiable Hypothesis"
  },
  {
   "q": "Where do architecture decisions sit relative to the three altitudes?",
   "opts": [
    "At intent altitude, alongside the problem statement",
    "At the middle altitude — the high-level shape, above individual ticket detail",
    "At task altitude, describing the exact code to write"
   ],
   "a": 1,
   "why": "Architecture decisions are the middle altitude — the high-level shape of the solution — deliberately one level above per-ticket implementation detail.",
   "lesson": "17-architecture-decisions",
   "n": 17,
   "title": "Architecture Decisions"
  },
  {
   "q": "Why should architecture decisions be grounded in the actual codebase rather than decided in the abstract?",
   "opts": [
    "Because the codebase is more interesting to read than the strategic doc",
    "It isn't necessary — architecture is a purely conceptual exercise",
    "Because decisions that ignore existing structure and seams tend to look fine on paper and fall apart once real code is involved"
   ],
   "a": 2,
   "why": "Grounding decisions in the actual codebase — its real structure and existing seams — is what separates a workable architecture decision from a guess made in the abstract.",
   "lesson": "17-architecture-decisions",
   "n": 17,
   "title": "Architecture Decisions"
  },
  {
   "q": "What should you do with a decision that's cheap and easy to reverse if it's wrong?",
   "opts": [
    "Schedule a dedicated planning session to deliberate carefully",
    "Decide it quickly and move on",
    "Build a spike before committing to it"
   ],
   "a": 1,
   "why": "Two-way doors are cheap to reverse and should be decided quickly; the mistake is spending heavy deliberation on something you could just as easily walk back from.",
   "lesson": "18-two-way-doors",
   "n": 18,
   "title": "Two-Way vs. One-Way Doors"
  }
 ],
 "m5": [
  {
   "q": "What actually determines whether a ticket is sized correctly?",
   "opts": [
    "Whether it's under some fixed line-count limit",
    "Whether it resolves to one testable concern",
    "Whether it fits in the agent's context window"
   ],
   "a": 1,
   "why": "Line count says nothing about whether a human can check the result. The bound is one testable concern per ticket.",
   "lesson": "19-slicing-tickets",
   "n": 19,
   "title": "Slicing the Work"
  },
  {
   "q": "Why does handing an agent an entire epic in one go tend to produce bad results?",
   "opts": [
    "It overloads the model and removes the human review checkpoint",
    "Agents refuse tasks above a certain size",
    "It costs significantly more in API usage"
   ],
   "a": 0,
   "why": "A huge task overwhelms the model into guessing and drift, and it removes the human checkpoint between small, reviewable pieces of work.",
   "lesson": "19-slicing-tickets",
   "n": 19,
   "title": "Slicing the Work"
  },
  {
   "q": "When should you write the detailed, one-pass-ready plan for an individual ticket?",
   "opts": [
    "Immediately, while slicing the whole epic",
    "Never — the agent should infer the plan on its own",
    "Later, inside the loop that picks that ticket up"
   ],
   "a": 2,
   "why": "Detailed, per-ticket planning happens just-in-time, inside the loop that picks the ticket up — not while slicing the epic.",
   "lesson": "19-slicing-tickets",
   "n": 19,
   "title": "Slicing the Work"
  },
  {
   "q": "What makes it safe to let the agent write every line of code in this loop?",
   "opts": [
    "The agent is only allowed to change small files",
    "A senior engineer watches every keystroke live",
    "Implementation is sandwiched between a plan the human owns and validation the human gates"
   ],
   "a": 2,
   "why": "Implementation is deliberately sandwiched between a human-owned plan and a human-gated validation — that's what makes handing over every line of code safe.",
   "lesson": "20-full-loop-end-to-end",
   "n": 20,
   "title": "The Full Loop, End to End"
  },
  {
   "q": "Why does validation happen as two separate passes rather than one?",
   "opts": [
    "To make the loop take longer on purpose",
    "\"Does it work\" and \"is it built well\" are different questions, and folding them together drops one",
    "Because a single agent session can't run tests"
   ],
   "a": 1,
   "why": "Implement proves the feature functions; the separate review pass judges whether the code is well built. They are deliberately not the same check.",
   "lesson": "20-full-loop-end-to-end",
   "n": 20,
   "title": "The Full Loop, End to End"
  },
  {
   "q": "What does running core loops in parallel actually buy you?",
   "opts": [
    "Throughput — the same work finishes in less wall-clock time",
    "Lower total cost for the same amount of work",
    "The ability to skip planning and validation entirely"
   ],
   "a": 0,
   "why": "Parallel loops let independent tickets build simultaneously, so the same total work finishes sooner — it's not free output and not several agents on one task.",
   "lesson": "21-parallel-loops",
   "n": 21,
   "title": "Running Loops in Parallel"
  },
  {
   "q": "Why does a git worktree give you a separate branch AND a separate file copy, rather than just one or the other?",
   "opts": [
    "The branch is only for looks; the file copy does all the real work",
    "Git requires a new branch any time a new folder is created",
    "The file copy stops agents from colliding on edits; the branch keeps each ticket's history clean"
   ],
   "a": 2,
   "why": "A worktree gives two levels of isolation: a separate file copy so agents can't collide on edits, and a separate branch so each stream of history stays clean.",
   "lesson": "21-parallel-loops",
   "n": 21,
   "title": "Running Loops in Parallel"
  },
  {
   "q": "Spaced recall — back in Clean Context, why did a fresh session get only the saved plan as input, with the earlier back-and-forth cleared out?",
   "opts": [
    "To save on storage space",
    "So implementation starts from a clean, uncluttered context instead of a chat full of exploratory back-and-forth",
    "Because agents cannot read long conversations at all"
   ],
   "a": 1,
   "why": "Clean Context is about keeping one session's context free of stale clutter before implementing; worktrees apply that same discipline across several sessions sharing a workspace at once.",
   "lesson": "21-parallel-loops",
   "n": 21,
   "title": "Running Loops in Parallel"
  }
 ],
 "m6": [
  {
   "q": "On an existing codebase, where should a rules file's content come from?",
   "opts": [
    "Whatever conventions you wish the team followed",
    "What the code actually does today",
    "A generic best-practices checklist"
   ],
   "a": 1,
   "why": "Rules must be derived from what the codebase actually does — writing aspirational rules on an existing project just teaches the agent something false.",
   "lesson": "22-rules",
   "n": 22,
   "title": "Rules"
  },
  {
   "q": "Why keep an always-loaded rules file short instead of comprehensive?",
   "opts": [
    "It loads on every task, so bloat crowds out what actually matters",
    "Long files are against the file format's rules",
    "Agents refuse to read files past a certain length"
   ],
   "a": 0,
   "why": "The rules file loads on every task, so anything long or generic in it crowds out the specific lines that actually matter.",
   "lesson": "22-rules",
   "n": 22,
   "title": "Rules"
  },
  {
   "q": "What is a skill, in plain terms?",
   "opts": [
    "A rule the agent must always obey",
    "A connection to an external tool",
    "A repeatable workflow packaged under a name you can trigger"
   ],
   "a": 2,
   "why": "A skill packages a repeated multi-step workflow under a name, so you trigger the whole routine instead of re-explaining it each time.",
   "lesson": "23-skills",
   "n": 23,
   "title": "Skills (Reusable Workflows)"
  },
  {
   "q": "Why doesn't having dozens of skills bloat every single task?",
   "opts": [
    "Only a short name and description stay always-visible; full detail loads on demand",
    "Skills are deleted automatically after one use",
    "The agent ignores skills unless you name them out loud"
   ],
   "a": 0,
   "why": "Progressive disclosure keeps only a short name and description always-visible; the full instructions load only once a skill is actually invoked.",
   "lesson": "23-skills",
   "n": 23,
   "title": "Skills (Reusable Workflows)"
  },
  {
   "q": "What's the core payoff of a subagent's isolated context?",
   "opts": [
    "It can run faster than the main agent",
    "Heavy digging happens elsewhere, and only a tight summary comes back",
    "It has access to different rules than the main agent"
   ],
   "a": 1,
   "why": "A subagent's separate context is what lets it do heavy digging without cluttering the main conversation — it hands back only a tight summary.",
   "lesson": "24-subagents",
   "n": 24,
   "title": "Subagents"
  },
  {
   "q": "Why use a separate subagent to review a change instead of asking the same agent that wrote it?",
   "opts": [
    "The agent that wrote the code is a biased judge of its own work",
    "The writing agent isn't allowed to read its own diffs",
    "Reviews require a different coding language"
   ],
   "a": 0,
   "why": "An agent judging its own code has no incentive to find its own flaws; a subagent with a fresh context and no memory of writing the code has no such bias.",
   "lesson": "24-subagents",
   "n": 24,
   "title": "Subagents"
  },
  {
   "q": "What problem does MCP actually solve?",
   "opts": [
    "It makes the model itself smarter",
    "It replaces the need for a rules file",
    "It gives agents and tools one shared way to connect, instead of custom work per integration"
   ],
   "a": 2,
   "why": "MCP is an open standard that lets any MCP-capable agent connect to any system that exposes an MCP server, the same way each time — instead of custom integration work per tool.",
   "lesson": "25-tools-and-mcp",
   "n": 25,
   "title": "Tools & Connections (MCP)"
  },
  {
   "q": "Without any tool connections, how does an agent answer a question about a live ticket or a database?",
   "opts": [
    "It automatically connects to whatever it needs",
    "It has to guess, or wait for you to paste the information in",
    "It refuses to answer any external question"
   ],
   "a": 1,
   "why": "Without a connection, the agent can only guess or wait for you to paste data in — a connection lets it read the real thing directly.",
   "lesson": "25-tools-and-mcp",
   "n": 25,
   "title": "Tools & Connections (MCP)"
  },
  {
   "q": "What does symbol-level navigation give an agent that blind text search doesn't?",
   "opts": [
    "Faster typing speed",
    "An understanding of code structure — the real definition and real references",
    "The ability to run tests automatically"
   ],
   "a": 1,
   "why": "Symbol-level navigation understands code structure — it finds the real definition and real references, the way go-to-definition and find-references work in an editor.",
   "lesson": "26-code-navigation",
   "n": 26,
   "title": "Code Navigation & Search"
  },
  {
   "q": "Why does blind text search get worse as a codebase grows larger?",
   "opts": [
    "Common names repeat across unrelated files, so matches turn into noise",
    "Large codebases disable search entirely",
    "Bigger files can no longer be opened by the agent"
   ],
   "a": 0,
   "why": "As a codebase grows, common names repeat across unrelated files, so plain-text matching returns more noise, costing time, tokens, and sometimes causing edits to the wrong place.",
   "lesson": "26-code-navigation",
   "n": 26,
   "title": "Code Navigation & Search"
  }
 ],
 "m7": [
  {
   "q": "In the layered picture of your system, what is the coding agent itself?",
   "opts": [
    "The context layer you author",
    "The base tool you choose, not build",
    "The core loop's four steps"
   ],
   "a": 1,
   "why": "The coding agent is Layer 0 — the harness you pick off the shelf. Your context layer and core loop sit above it and are what you actually build.",
   "lesson": "28-choosing-your-agent",
   "n": 28,
   "title": "Choosing Your Coding Agent"
  },
  {
   "q": "You switch from one coding agent to another after two months. What has to happen to your rules and workflows?",
   "opts": [
    "You rebuild everything from scratch",
    "They translate over with minor convention changes",
    "They stop working entirely"
   ],
   "a": 1,
   "why": "Because the context layer and the loop are tool-agnostic, moving to a new agent is mostly a naming/convention translation, not starting over.",
   "lesson": "28-choosing-your-agent",
   "n": 28,
   "title": "Choosing Your Coding Agent"
  },
  {
   "q": "What's the risk this lesson warns against?",
   "opts": [
    "Spending too long comparing tools instead of building your system",
    "Picking a terminal-based agent over an editor-based one",
    "Using more than one coding agent at all"
   ],
   "a": 0,
   "why": "Over-investing in tool comparison delays the thing that actually produces reliable results: the system you build around whichever tool you pick.",
   "lesson": "28-choosing-your-agent",
   "n": 28,
   "title": "Choosing Your Coding Agent"
  },
  {
   "q": "What actually changes when you move a core loop into a background or CI-triggered agent?",
   "opts": [
    "The four steps of the loop are replaced with new ones",
    "Where and when the loop runs, and whether a human watches it",
    "The rules and context layer no longer apply"
   ],
   "a": 1,
   "why": "Scaling here means moving a loop you already trust off your screen — background, remote, or CI-triggered — not changing what the loop does.",
   "lesson": "29-scaling-and-automation",
   "n": 29,
   "title": "Scaling & Automation"
  },
  {
   "q": "Why should you get a loop working reliably by hand before automating it in CI?",
   "opts": [
    "Automation only works on greenfield projects",
    "CI platforms cannot run coding agents",
    "Automation multiplies whatever process it's given, good or bad"
   ],
   "a": 2,
   "why": "Automation amplifies whatever process feeds it. A weak, unvalidated loop just produces weak results faster and at greater scale — so trust the loop by hand before wiring it to run unattended.",
   "lesson": "29-scaling-and-automation",
   "n": 29,
   "title": "Scaling & Automation"
  },
  {
   "q": "Quick recall: what are the four steps of the core loop, in order?",
   "opts": [
    "Plan, Research, Validate, Implement",
    "Write, Test, Ship, Review",
    "Research, Plan, Implement, Validate"
   ],
   "a": 2,
   "why": "Research, Plan, Implement, Validate — the four-step rhythm you run on one small piece of work at a time.",
   "lesson": "30-your-first-week",
   "n": 30,
   "title": "Your First Week"
  },
  {
   "q": "What's the four-stage arc this course walked you through?",
   "opts": [
    "Plan, Build, Test, Deploy",
    "Use, Understand, Evolve, Scale",
    "Prompt, Generate, Accept, Ship"
   ],
   "a": 1,
   "why": "Use, Understand, Evolve, Scale is the arc: get it working, learn each piece, combine pieces into bigger workflows, then move reliable loops beyond one person at one keyboard.",
   "lesson": "30-your-first-week",
   "n": 30,
   "title": "Your First Week"
  },
  {
   "q": "If you remember only one sentence from this whole course, which is it?",
   "opts": [
    "The bottleneck was never the model — it's the system around it",
    "Always pick the newest coding agent available",
    "Bigger models always produce better code"
   ],
   "a": 0,
   "why": "Every lesson pointed back to this: the model was never the limiting factor. The system you build around it — context and a repeatable loop — is what determines whether results are reliable.",
   "lesson": "30-your-first-week",
   "n": 30,
   "title": "Your First Week"
  }
 ]
};
