/* GENERATED by tools/quiz-data.mjs — do not edit. Re-run after editing lessons. */
window.QUIZ = {
 "m1": [
  {
   "q": "Why does the <em>quality of the instructions</em> matter so much in software?",
   "opts": [
    "Computers are usually a bit unreliable",
    "A computer does exactly what it's told — nothing more, nothing less",
    "Instructions are the slowest part of an app"
   ],
   "a": 1,
   "why": "A computer does exactly what it's told, with no common sense to fill gaps — so the instructions have to be right.",
   "lesson": "01-what-is-software",
   "n": 1,
   "title": "What Software Really Is"
  },
  {
   "q": "The AI shows you a feature working in a quick demo. What has that actually proven?",
   "opts": [
    "That it's secure and ready for users",
    "That it will handle heavy traffic",
    "Only that it ran once, under those exact conditions"
   ],
   "a": 2,
   "why": "Running once in a demo says nothing about safety, scale, or maintainability — those are separate questions.",
   "lesson": "01-what-is-software",
   "n": 1,
   "title": "What Software Really Is"
  },
  {
   "q": "In the restaurant analogy, which part is the \"kitchen\" — the brain that does the work?",
   "opts": [
    "The frontend",
    "The backend",
    "The database"
   ],
   "a": 1,
   "why": "The backend is the kitchen — the brain that does the work and enforces the rules, out of the customer's sight.",
   "lesson": "02-the-stack",
   "n": 2,
   "title": "The Stack"
  },
  {
   "q": "An AI shows you a beautiful screen, but nothing you type is saved once you close the app. What's most likely missing?",
   "opts": [
    "Just better colors",
    "A faster internet connection",
    "A real backend and database behind the frontend"
   ],
   "a": 2,
   "why": "A pretty frontend with no backend or database behind it is a stage set — it looks real but nothing actually happens or gets saved.",
   "lesson": "02-the-stack",
   "n": 2,
   "title": "The Stack"
  },
  {
   "q": "Which one sends the request, and which one sends back the response?",
   "opts": [
    "The client sends the request; the server sends the response",
    "The server sends the request; the client sends the response",
    "They both send requests to each other at the same time"
   ],
   "a": 0,
   "why": "The client sends the request; the server is the always-on computer elsewhere that sends back the response.",
   "lesson": "03-client-and-server",
   "n": 3,
   "title": "Client & Server"
  },
  {
   "q": "What is an API, in plain terms?",
   "opts": [
    "The screens and buttons you see in an app",
    "The agreed menu of requests a server accepts and knows how to answer",
    "The physical cables that carry internet traffic"
   ],
   "a": 1,
   "why": "An API is the agreed menu of requests a server will accept and answer — like a waiter only taking orders from the menu.",
   "lesson": "03-client-and-server",
   "n": 3,
   "title": "Client & Server"
  },
  {
   "q": "What is a \"dependency,\" in plain terms?",
   "opts": [
    "A part of the app that's broken and needs fixing",
    "Pre-built code someone else wrote that your software relies on",
    "The programming language the app is written in"
   ],
   "a": 1,
   "why": "Frameworks and libraries are pre-built chunks of other people's code you build on — like pre-made windows and doors when building a house.",
   "lesson": "04-languages-and-dependencies",
   "n": 4,
   "title": "Languages & Dependencies"
  },
  {
   "q": "What's the main risk of relying on someone else's pre-built code?",
   "opts": [
    "It always makes the app slower",
    "It's illegal to use without permission",
    "You inherit its bugs and security holes, including future ones"
   ],
   "a": 2,
   "why": "You inherit a dependency's bugs and security holes too — including ones discovered after you already built on top of it.",
   "lesson": "04-languages-and-dependencies",
   "n": 4,
   "title": "Languages & Dependencies"
  },
  {
   "q": "Spaced recall from Lesson 1: why does the quality of the instructions matter so much in software?",
   "opts": [
    "Because computers are slow at reading long files",
    "Because a computer does exactly what it's told, with no common sense to fill in gaps",
    "Because instructions are only a small part of any app"
   ],
   "a": 1,
   "why": "Software is precise instructions a computer follows literally — with no common sense to fill in gaps, as Lesson 1 covered.",
   "lesson": "05-how-apps-get-built",
   "n": 5,
   "title": "How Apps Get Built"
  },
  {
   "q": "Spaced recall from Lesson 1: an AI shows a feature working once in a demo. What has that actually proven?",
   "opts": [
    "That it's ready to ship to real users",
    "That it will hold up under heavy traffic",
    "Only that it ran once, under those exact conditions"
   ],
   "a": 2,
   "why": "Working once in a demo only proves it ran under those exact conditions — not that it's safe, tested, or ready for real users, as Lesson 1 covered.",
   "lesson": "05-how-apps-get-built",
   "n": 5,
   "title": "How Apps Get Built"
  }
 ],
 "m2": [
  {
   "q": "What makes a database different from the app's regular short-term memory?",
   "opts": [
    "It's faster to read from",
    "It keeps information even after the app closes or the device restarts",
    "It only works for text, not numbers"
   ],
   "a": 1,
   "why": "A database is separate, permanent storage — it's built to survive the app closing, restarting, or updating.",
   "lesson": "06-what-is-a-database",
   "n": 6,
   "title": "What a Database Is"
  },
  {
   "q": "In a database table, what do the rows represent?",
   "opts": [
    "The names of the columns",
    "Rules about what data is allowed",
    "Individual records, like one specific user or order"
   ],
   "a": 2,
   "why": "Rows are individual records (one user, one order); columns are the fields every record shares (name, email, date).",
   "lesson": "06-what-is-a-database",
   "n": 6,
   "title": "What a Database Is"
  },
  {
   "q": "Why does a real app need a database instead of just a spreadsheet?",
   "opts": [
    "A database handles many users at once, stays fast at scale, and can enforce rules a spreadsheet can't",
    "Spreadsheets can't store text, only numbers",
    "Databases are always free and spreadsheets cost money"
   ],
   "a": 0,
   "why": "Spreadsheets aren't built for many simultaneous writers, huge scale, or enforcing data rules — databases are.",
   "lesson": "06-what-is-a-database",
   "n": 6,
   "title": "What a Database Is"
  },
  {
   "q": "What does \"data modeling\" mean?",
   "opts": [
    "Choosing the colors and fonts for the app's screens",
    "Deciding what information the app stores and how the pieces relate to each other",
    "Testing the app with fake users before launch"
   ],
   "a": 1,
   "why": "Data modeling is naming what you store and how it relates — like users having orders, and orders having items.",
   "lesson": "07-modeling-your-data",
   "n": 7,
   "title": "Modeling Your Data"
  },
  {
   "q": "Why is the data model the most expensive thing to change later?",
   "opts": [
    "Because databases charge money per table",
    "Because it requires learning a new programming language",
    "Because every screen, feature, and existing piece of saved data is built assuming that shape"
   ],
   "a": 2,
   "why": "Everything the app does gets built on top of the model, so reshaping it later means touching all of that — plus data already saved in the old shape.",
   "lesson": "07-modeling-your-data",
   "n": 7,
   "title": "Modeling Your Data"
  },
  {
   "q": "What does \"state\" mean in software?",
   "opts": [
    "Everything the app currently knows about what's going on right now",
    "The physical location of the company's servers",
    "A list of bugs that haven't been fixed yet"
   ],
   "a": 0,
   "why": "State is simply everything the app currently knows — logged in or not, what's in the cart, which tab is open.",
   "lesson": "08-state-and-storage",
   "n": 8,
   "title": "State & Storage"
  },
  {
   "q": "Someone complains their shopping cart emptied itself overnight. What's the most likely cause?",
   "opts": [
    "The database lost power",
    "The cart was only kept in a temporary session or memory, not saved to the database",
    "The user's internet connection was too slow"
   ],
   "a": 1,
   "why": "A cart the user expects to survive should live in the database, not just in a session or in-memory state that disappears when they leave.",
   "lesson": "08-state-and-storage",
   "n": 8,
   "title": "State & Storage"
  },
  {
   "q": "Why does reshaping your data model later (from Lesson 7) require special care?",
   "opts": [
    "Because it's against the law to change a database once it's created",
    "Because real data is already sitting on top of the old shape, and a careless change can lose or scramble it",
    "Because databases can only be changed once a year"
   ],
   "a": 1,
   "why": "A migration is a careful, tracked, tested change to the database's shape — designed specifically to not damage existing data.",
   "lesson": "09-migrations-and-backups",
   "n": 9,
   "title": "Migrations & Backups"
  },
  {
   "q": "What's the difference between a migration and a backup?",
   "opts": [
    "They're two names for the same thing",
    "A migration copies data elsewhere; a backup changes its shape",
    "A migration is a tracked change to the data's shape; a backup is a safety copy in case something goes wrong"
   ],
   "a": 2,
   "why": "A migration is the tracked, careful change itself; a backup is the separate safety copy in case anything — including the migration — goes wrong.",
   "lesson": "09-migrations-and-backups",
   "n": 9,
   "title": "Migrations & Backups"
  },
  {
   "q": "Why should you actually test restoring from a backup, not just take backups?",
   "opts": [
    "Because a backup that's never been restored might not actually work when you need it",
    "Because backups expire after 24 hours",
    "Because it makes the database run faster"
   ],
   "a": 0,
   "why": "An untested backup is just an assumption — restoring it is the only way to confirm it actually works when you need it.",
   "lesson": "09-migrations-and-backups",
   "n": 9,
   "title": "Migrations & Backups"
  }
 ],
 "m3": [
  {
   "q": "What is a \"requirement,\" in plain terms?",
   "opts": [
    "The programming language the AI uses",
    "A plain statement of what the software must do, written before you build it",
    "A bug that was found after launch"
   ],
   "a": 1,
   "why": "A requirement is what the software must do — a plain sentence written down before building, so everyone (including the AI) is aiming at the same target.",
   "lesson": "10-what-done-means",
   "n": 10,
   "title": "What 'Done' Really Means"
  },
  {
   "q": "Why do edge cases matter if the demo already worked?",
   "opts": [
    "They don't — if the demo works, the feature is done",
    "They're rare hacker tricks that only affect big companies",
    "They're realistic inputs — empty, duplicate, malicious — that ordinary users hit regularly"
   ],
   "a": 2,
   "why": "Edge cases — empty, huge, wrong, zero, negative, duplicate, malicious — are realistic inputs real users hit constantly. The happy path only proves the ideal case works.",
   "lesson": "10-what-done-means",
   "n": 10,
   "title": "What 'Done' Really Means"
  },
  {
   "q": "What should a tiny \"definition of done\" include?",
   "opts": [
    "The requirement, the edge cases to check, and what \"handled\" looks like",
    "Only the requirement — edge cases can be figured out later",
    "A full technical architecture diagram"
   ],
   "a": 0,
   "why": "Definition of done = requirement + the edge cases you care about + what 'handled' looks like. Handing that to the AI turns a guess into a spec.",
   "lesson": "10-what-done-means",
   "n": 10,
   "title": "What 'Done' Really Means"
  },
  {
   "q": "What does a test actually give you that manually trying the feature once doesn't?",
   "opts": [
    "A nicer-looking interface",
    "An automatic, repeatable check that keeps proving the behavior still works as things change",
    "Faster software overall"
   ],
   "a": 1,
   "why": "A test is a small automated check — it proves a behavior works now, and keeps proving it every time something changes, without you manually re-checking.",
   "lesson": "11-testing-basics",
   "n": 11,
   "title": "Testing, Explained"
  },
  {
   "q": "Which type of test acts most like a real user clicking through the product?",
   "opts": [
    "Unit test",
    "Integration test",
    "End-to-end test"
   ],
   "a": 2,
   "why": "End-to-end tests act like a real user clicking through the actual product from start to finish — the broadest of the three common types.",
   "lesson": "11-testing-basics",
   "n": 11,
   "title": "Testing, Explained"
  },
  {
   "q": "Why does AI-written code need tests more, not less?",
   "opts": [
    "Because you didn't write it, so you need proof it does what it should — not just a read-through",
    "Because AI code is always buggier than human code",
    "It doesn't — AI code is already tested by the AI itself"
   ],
   "a": 0,
   "why": "You didn't write the AI's code, so you can't fully vouch for it from reading alone — tests give you proof, not just an impression, which matters more, not less, for AI-written code.",
   "lesson": "11-testing-basics",
   "n": 11,
   "title": "Testing, Explained"
  },
  {
   "q": "What does it mean, in plain terms, that a bug exists?",
   "opts": [
    "Some instruction was wrong, incomplete, or missed a case the computer was actually given",
    "The computer had a temporary glitch with no real cause",
    "The user did something they weren't supposed to do"
   ],
   "a": 0,
   "why": "Computers follow instructions exactly with no common sense — so a bug always traces back to an instruction that was wrong, incomplete, or missed a case.",
   "lesson": "12-bugs-and-debugging",
   "n": 12,
   "title": "Bugs & Debugging"
  },
  {
   "q": "What's the correct order for debugging?",
   "opts": [
    "Guess at a fix, then see if it happens to work",
    "Reproduce the bug, find the cause, then fix it",
    "Fix it first, then check whether it was actually broken"
   ],
   "a": 1,
   "why": "Reproduce it, find the cause, then fix it — in that order. Guessing at a fix before reproducing the bug is not real debugging.",
   "lesson": "12-bugs-and-debugging",
   "n": 12,
   "title": "Bugs & Debugging"
  },
  {
   "q": "What makes a bug report actually useful?",
   "opts": [
    "A long, detailed description of how frustrating the bug is",
    "A screenshot alone, with no other context",
    "Steps to reproduce it, plus what was expected versus what actually happened"
   ],
   "a": 2,
   "why": "A good bug report gives exact reproduction steps plus expected vs. actual behavior — that lets whoever fixes it (human or AI) skip straight to finding the cause.",
   "lesson": "12-bugs-and-debugging",
   "n": 12,
   "title": "Bugs & Debugging"
  },
  {
   "q": "Do you need to know how to code to review code well?",
   "opts": [
    "Yes, review is only meaningful if you could have written it yourself",
    "No — asking sharp questions and evaluating the plain-English answers is a learnable, non-technical skill",
    "No, because AI code never needs reviewing"
   ],
   "a": 1,
   "why": "Code review asks whether something is correct, clear, and safe — a judgment call anyone can learn to make by asking sharp questions and reading the answers, not a skill limited to people who can write code.",
   "lesson": "13-reviewing-code",
   "n": 13,
   "title": "Reviewing Code"
  }
 ],
 "m4": [
  {
   "q": "What does \"good security\" actually mean for an everyday app?",
   "opts": [
    "The app can never be broken into, under any circumstances",
    "Valuable stuff is hard to reach, and damage is limited if something slips through",
    "Only large companies need to think about it"
   ],
   "a": 1,
   "why": "Security assumes attempts at misuse will happen and focuses on making the valuable stuff hard to reach and limiting damage — not on being unbreakable.",
   "lesson": "14-security-mindset",
   "n": 14,
   "title": "The Security Mindset"
  },
  {
   "q": "What is \"defense in depth\"?",
   "opts": [
    "Using several layers of protection, so one failure doesn't mean total loss",
    "Writing one very strong password",
    "Hiring a security expert instead of thinking about it yourself"
   ],
   "a": 0,
   "why": "Defense in depth means using several layers so that one failure doesn't expose everything — like a locked front door plus a safe inside.",
   "lesson": "14-security-mindset",
   "n": 14,
   "title": "The Security Mindset"
  },
  {
   "q": "Why do we say \"never trust user input\"?",
   "opts": [
    "Because most users are trying to cause harm",
    "Because forms are slower to process than other code",
    "Because the app can't tell a real customer's input from a deliberately harmful one without checking"
   ],
   "a": 2,
   "why": "Treating all user input as potentially hostile until it's checked is one of the core habits behind almost every security lesson that follows.",
   "lesson": "14-security-mindset",
   "n": 14,
   "title": "The Security Mindset"
  },
  {
   "q": "What's the difference between authentication and authorization?",
   "opts": [
    "They're two names for the same login step",
    "Authentication proves who you are; authorization checks what you're allowed to do",
    "Authorization happens first, then authentication"
   ],
   "a": 1,
   "why": "Authentication proves who you are (login); authorization checks what that person is allowed to do. They are separate steps, checked at different times.",
   "lesson": "15-login-and-permissions",
   "n": 15,
   "title": "Login & Permissions"
  },
  {
   "q": "A user changes the number in a web address and sees someone else's order. What most likely went wrong?",
   "opts": [
    "The password wasn't hashed",
    "The user wasn't logged in at all",
    "The app checked that the user was logged in, but never checked that the order belonged to them"
   ],
   "a": 2,
   "why": "The classic disaster is checking WHO someone is but never checking WHAT they're allowed to reach — letting any logged-in user view others' data by changing an ID.",
   "lesson": "15-login-and-permissions",
   "n": 15,
   "title": "Login & Permissions"
  },
  {
   "q": "Why should passwords be stored \"hashed\" instead of as plain text?",
   "opts": [
    "So a stolen database doesn't hand attackers everyone's real password",
    "So the app loads pages faster",
    "So users can recover their exact password if they forget it"
   ],
   "a": 0,
   "why": "Hashing is one-way scrambling — the app compares scrambled versions and never needs to store the real password, so a stolen database doesn't hand over plain passwords.",
   "lesson": "15-login-and-permissions",
   "n": 15,
   "title": "Login & Permissions"
  },
  {
   "q": "Why is pasting a real API key into code and pushing it to a public repository so dangerous?",
   "opts": [
    "It's not dangerous unless the app is already popular",
    "Bots scan public repositories for keys constantly, and a leaked one can be found and used within minutes",
    "It only slows down how fast the code runs"
   ],
   "a": 1,
   "why": "Bots continuously scan public repositories for patterns that look like API keys, and leaked keys are typically found and abused within minutes.",
   "lesson": "16-secrets-and-keys",
   "n": 16,
   "title": "Secrets & Keys"
  },
  {
   "q": "What's the fix for keeping secrets out of shared code?",
   "opts": [
    "Write the secret in a comment so it's easy to find",
    "Change the secret every day",
    "Store it as an environment variable, kept separate from the code"
   ],
   "a": 2,
   "why": "Environment variables keep secrets outside the code entirely, in separate configuration, so the code itself can be shared or pushed without exposing them.",
   "lesson": "16-secrets-and-keys",
   "n": 16,
   "title": "Secrets & Keys"
  },
  {
   "q": "What is \"injection,\" in plain terms?",
   "opts": [
    "Input that tricks the app into running it as a command instead of treating it as plain data",
    "An app running too slowly under heavy traffic",
    "A user forgetting their password"
   ],
   "a": 0,
   "why": "Injection is when input crafted to look like a command is followed by the underlying system instead of treated as plain data.",
   "lesson": "17-common-vulnerabilities",
   "n": 17,
   "title": "Common Vulnerabilities"
  },
  {
   "q": "A user changes a number in a web address and sees another customer's private order. What category of problem is this?",
   "opts": [
    "Cross-site scripting",
    "Injection",
    "Exposed data"
   ],
   "a": 2,
   "why": "Exposed data happens when private info is reachable simply by editing an ID or address, because the app never rechecks who owns that data.",
   "lesson": "17-common-vulnerabilities",
   "n": 17,
   "title": "Common Vulnerabilities"
  }
 ],
 "m5": [
  {
   "q": "What is staging mainly for?",
   "opts": [
    "It's where you write brand-new code from scratch",
    "Rehearsing changes in a copy that mimics production, before real users see them",
    "It's just a backup copy of production in case something breaks"
   ],
   "a": 1,
   "why": "Staging exists specifically to mimic production closely enough that testing there predicts what will happen live — without any real-user risk.",
   "lesson": "19-environments",
   "n": 19,
   "title": "Environments"
  },
  {
   "q": "\"It works on my machine\" but breaks for users usually means what?",
   "opts": [
    "The development and production environments differ in some way that matters",
    "The user's device is broken",
    "The code has no bugs, so it must be a fluke"
   ],
   "a": 0,
   "why": "The classic cause is that the environments differ — different data, settings, or versions — not that the code itself is unreliable.",
   "lesson": "19-environments",
   "n": 19,
   "title": "Environments"
  },
  {
   "q": "Where should a risky, uncertain change be tested first?",
   "opts": [
    "Directly in production, since that's the real conditions",
    "Nowhere — just ship it and watch for complaints",
    "In staging, a rehearsal copy that mimics production"
   ],
   "a": 2,
   "why": "Production holds real user data and real consequences — risky changes belong in staging first, never tried live 'to see what happens.'",
   "lesson": "19-environments",
   "n": 19,
   "title": "Environments"
  },
  {
   "q": "What does \"deploying\" software actually mean?",
   "opts": [
    "Writing the first draft of the code",
    "Testing a change on your own workbench",
    "Publishing a change to the live environment users can reach"
   ],
   "a": 2,
   "why": "Deploying specifically means publishing to production — the live environment real users can reach — not just finishing the code.",
   "lesson": "20-deployment",
   "n": 20,
   "title": "Deployment"
  },
  {
   "q": "What is CI/CD mainly for?",
   "opts": [
    "Making the software run faster for users",
    "Automatically checking and shipping changes so deploys aren't risky manual events",
    "Choosing a domain name for your website"
   ],
   "a": 1,
   "why": "CI/CD is an automated pipeline of checks and steps, so shipping doesn't rely on a person remembering everything correctly under pressure.",
   "lesson": "20-deployment",
   "n": 20,
   "title": "Deployment"
  },
  {
   "q": "Why roll a change out to a small group of users before everyone?",
   "opts": [
    "To limit how many people a hidden problem could affect before it's caught",
    "Because hosting charges less for fewer users",
    "It's required by every domain name registrar"
   ],
   "a": 0,
   "why": "Gradual rollout limits how many users a mistake can reach before it's caught — some problems only surface with real traffic.",
   "lesson": "20-deployment",
   "n": 20,
   "title": "Deployment"
  },
  {
   "q": "What's the main difference between logs and monitoring?",
   "opts": [
    "They're two names for the exact same thing",
    "Logs are a diary you dig through afterward; monitoring is ongoing automatic watching",
    "Logs are for developers, monitoring is only for users"
   ],
   "a": 1,
   "why": "Logs are the timestamped diary you dig through after the fact; monitoring is the ongoing, automatic watching of live health.",
   "lesson": "21-monitoring-and-logs",
   "n": 21,
   "title": "Monitoring & Logs"
  },
  {
   "q": "What is an alert for?",
   "opts": [
    "Automatically notifying a human when monitoring spots a real problem",
    "Recording every single thing the software ever does",
    "Making the software run faster under heavy traffic"
   ],
   "a": 0,
   "why": "Alerts exist specifically so a human finds out from the system, not from an angry user noticing something broken first.",
   "lesson": "21-monitoring-and-logs",
   "n": 21,
   "title": "Monitoring & Logs"
  },
  {
   "q": "Why is \"no one has complained\" not proof that live software is healthy?",
   "opts": [
    "Because users always complain immediately about everything",
    "Because complaints only matter in staging, not production",
    "Because a problem can run unnoticed for a long time without monitoring in place"
   ],
   "a": 2,
   "why": "Silence from monitoring or logs isn't proof of health — without watching, a problem can run unnoticed for a long time.",
   "lesson": "21-monitoring-and-logs",
   "n": 21,
   "title": "Monitoring & Logs"
  },
  {
   "q": "What's the real measure of good software when it comes to failure?",
   "opts": [
    "Whether it ever breaks at all",
    "How gracefully it fails when it inevitably does break",
    "How fast it runs when everything is working"
   ],
   "a": 1,
   "why": "Perfection isn't realistic — the real measure of quality is how contained and graceful the failure is when it happens.",
   "lesson": "22-when-it-breaks",
   "n": 22,
   "title": "When It Breaks"
  }
 ],
 "m6": [
  {
   "q": "What does \"latency\" mean?",
   "opts": [
    "The total number of features in an app",
    "The wait between doing something and getting a result",
    "How many people are using the app at once"
   ],
   "a": 1,
   "why": "Latency is specifically the wait between an action and the result — the gap performance is trying to shrink.",
   "lesson": "23-performance",
   "n": 23,
   "title": "Performance"
  },
  {
   "q": "Why is speed considered a \"real feature\" even though it's rarely requested explicitly?",
   "opts": [
    "Because slow software loses people even when nobody files a complaint",
    "Because speed is required by law for most software",
    "Because AI can only build fast software, never slow software"
   ],
   "a": 0,
   "why": "People rarely complain about slowness in words — they just quietly abandon the slow experience.",
   "lesson": "23-performance",
   "n": 23,
   "title": "Performance"
  },
  {
   "q": "Why might a page with a visible loading spinner feel faster than a silent, frozen page — even if the frozen one technically loads sooner?",
   "opts": [
    "Spinners make the computer process the request faster",
    "Users always prefer more visual movement on screen",
    "Perceived speed depends on managing attention, not just the raw clock time"
   ],
   "a": 2,
   "why": "A visible, honest wait (spinner, progress) tends to feel less frustrating than a silent freeze, even if the freeze resolves slightly faster.",
   "lesson": "23-performance",
   "n": 23,
   "title": "Performance"
  },
  {
   "q": "What does \"scale\" describe?",
   "opts": [
    "How many features an app has",
    "How well the software keeps working as the number of users grows",
    "How pretty the app's design is"
   ],
   "a": 1,
   "why": "Scale is specifically about how usage growth affects the software — small-scale success doesn't predict large-scale success.",
   "lesson": "24-scale",
   "n": 24,
   "title": "Scale"
  },
  {
   "q": "What's the difference between \"scaling up\" and \"scaling out\"?",
   "opts": [
    "They're two names for the same thing",
    "Scaling up adds more servers; scaling out gets one bigger server",
    "Scaling up gets a more powerful single machine; scaling out adds more machines sharing the work"
   ],
   "a": 2,
   "why": "Scaling up means a bigger single machine; scaling out means adding more machines to share the load.",
   "lesson": "24-scale",
   "n": 24,
   "title": "Scale"
  },
  {
   "q": "What's the smart approach to planning for scale on a new product?",
   "opts": [
    "Build for what you actually need now, but avoid choices that would be painful to undo later",
    "Always design for a million users from day one, no matter the product's size",
    "Ignore scale entirely until something actually breaks"
   ],
   "a": 0,
   "why": "The sensible middle ground is building for actual current size plus headroom, while avoiding choices that are hard to undo — not swinging to either extreme.",
   "lesson": "24-scale",
   "n": 24,
   "title": "Scale"
  },
  {
   "q": "What is \"caching,\" in plain terms?",
   "opts": [
    "Keeping a ready-made copy of something expensive, so you don't redo the work each time",
    "Deleting old data to save space",
    "Making a server bigger to handle more users"
   ],
   "a": 0,
   "why": "Caching is exactly this: saving the result of expensive work once, and reusing it instead of redoing it every time.",
   "lesson": "25-caching-and-optimizing",
   "n": 25,
   "title": "Caching & Optimizing"
  },
  {
   "q": "What does a database \"index\" do?",
   "opts": [
    "It stores a permanent backup of all the data",
    "It helps the database find records quickly, like a book's table of contents",
    "It makes the database bigger to hold more information"
   ],
   "a": 1,
   "why": "An index works like a table of contents — it lets the database jump to the right place instead of scanning every record.",
   "lesson": "25-caching-and-optimizing",
   "n": 25,
   "title": "Caching & Optimizing"
  },
  {
   "q": "Why is \"premature optimization\" considered a trap?",
   "opts": [
    "Because fast software is always worse for users",
    "Because optimizing is illegal without special training",
    "Because it spends real effort making something fast before you know it needs to be, often making things more complicated for no benefit"
   ],
   "a": 2,
   "why": "Premature optimization means spending effort making something fast before confirming it's slow or even correct — usually wasted effort.",
   "lesson": "25-caching-and-optimizing",
   "n": 25,
   "title": "Caching & Optimizing"
  },
  {
   "q": "How is running software typically billed?",
   "opts": [
    "A single flat fee, paid once, forever",
    "Usually by usage — how much you store, move, or call, over time",
    "It's always free once the software is built"
   ],
   "a": 1,
   "why": "Almost every ongoing software cost — servers, storage, data transfer, APIs — is billed based on how much you actually use, not a flat fee.",
   "lesson": "26-cost",
   "n": 26,
   "title": "The Cost of Running It"
  }
 ],
 "m7": [
  {
   "q": "Why does a precise brief matter so much when directing an AI coding agent?",
   "opts": [
    "AI agents are slower with vague requests",
    "The AI does exactly what it's told, not what you meant — vague in means vague out",
    "Precise briefs are required by law for AI tools"
   ],
   "a": 1,
   "why": "An AI does exactly what it's told, not what you meant — so a precise brief (requirement + edge cases + constraints) is what closes that gap.",
   "lesson": "27-directing-ai",
   "n": 27,
   "title": "Directing the AI"
  },
  {
   "q": "What's the benefit of asking an AI to explain its plan before writing code?",
   "opts": [
    "It makes the AI write faster",
    "It's required — AI can't write code without a plan",
    "It catches misunderstandings early, while they're cheap to fix"
   ],
   "a": 2,
   "why": "Asking for the plan first surfaces misunderstandings while they're still sentences you can correct — not code you have to unwind after the fact.",
   "lesson": "27-directing-ai",
   "n": 27,
   "title": "Directing the AI"
  },
  {
   "q": "Why build in small steps rather than requesting \"the whole app\" at once?",
   "opts": [
    "Small steps are easier to review, and narrow down where problems come from",
    "AI agents can only write a few lines at a time",
    "It's cheaper, because AI charges per app"
   ],
   "a": 0,
   "why": "Small steps keep each request narrow enough to review properly, and narrow the blame when something's wrong.",
   "lesson": "27-directing-ai",
   "n": 27,
   "title": "Directing the AI"
  },
  {
   "q": "How does a non-coder meaningfully review AI-written code?",
   "opts": [
    "By reading every line and understanding the syntax",
    "By asking targeted questions and requiring the AI to show evidence, not just claims",
    "By trusting the AI's confidence level"
   ],
   "a": 1,
   "why": "You review by asking the AI targeted questions and judging its answers and evidence — not by reading the code yourself.",
   "lesson": "28-reviewing-ai-output",
   "n": 28,
   "title": "Reviewing AI's Work"
  },
  {
   "q": "The AI says \"yes, this is fully tested and secure\" with no example. What should you do?",
   "opts": [
    "Accept it — the AI knows its own code best",
    "Assume it's lying and start over",
    "Ask it to show you the specific test or check that proves the claim"
   ],
   "a": 2,
   "why": "Confident answers without a concrete example are exactly the case where you should ask the AI to point to the specific proof.",
   "lesson": "28-reviewing-ai-output",
   "n": 28,
   "title": "Reviewing AI's Work"
  },
  {
   "q": "What is \"technical debt,\" in plain terms?",
   "opts": [
    "The future cost of a shortcut taken today",
    "Money owed to a software vendor",
    "A bug that crashes the app"
   ],
   "a": 0,
   "why": "Technical debt is the future cost of a shortcut taken today — reasonable if it's deliberate and tracked, dangerous if it's accidental and forgotten.",
   "lesson": "29-maintainability",
   "n": 29,
   "title": "Maintainability & Debt"
  },
  {
   "q": "Why does maintainability matter more, not less, when an AI is writing the code?",
   "opts": [
    "AI-written code is always messier than human-written code",
    "AI can produce a mountain of code fast — a mountain of messy code is still a liability",
    "AI cannot write maintainable code at all"
   ],
   "a": 1,
   "why": "AI can produce a huge volume of code fast — which means messy code piles up just as fast, and it's still a liability regardless of how quickly it was written.",
   "lesson": "29-maintainability",
   "n": 29,
   "title": "Maintainability & Debt"
  },
  {
   "q": "Back to where we started: what does an AI demo running successfully actually prove?",
   "opts": [
    "That it's ready for real users",
    "That it's secure and well-tested",
    "Only that it ran once, under those exact conditions — nothing about safety, scale, or cost"
   ],
   "a": 2,
   "why": "A demo proves the happy path ran once, under ideal conditions. Safety, scale, cost, and maintainability are separate questions a demo never answers — that's the whole point of Lesson 1, and this checklist.",
   "lesson": "30-your-shipping-checklist",
   "n": 30,
   "title": "Your Shipping Checklist"
  },
  {
   "q": "What should a written \"definition of done\" include, before you ask an AI to build a feature?",
   "opts": [
    "Just a rough idea — details can come later",
    "The requirement, the edge cases to check, and what \"handled\" looks like",
    "A full line-by-line code review"
   ],
   "a": 1,
   "why": "A definition of done is the requirement, the edge cases, and what 'handled' means — written down before building, so 'done' isn't just whatever the AI happened to produce.",
   "lesson": "30-your-shipping-checklist",
   "n": 30,
   "title": "Your Shipping Checklist"
  }
 ]
};
