/* quiz-data.mjs — harvest the inline .quiz self-checks in each course's lessons
   into a scored per-module set. Run from the repo root:  node tools/quiz-data.mjs
   (add --check to validate without writing).
   For each course it reads every lessons/*.html, regex-extracts each
   <div class="quiz" data-answer data-why>…<p class="q">…</p><button>…</button>…</div>,
   groups the questions by their lesson's module, caps each module at 10, and writes
   courses/<course>/quiz-data.js = window.QUIZ = { m1:[…], … }.
   Idempotent: re-run after editing any lesson's quiz blocks. No deps. */
import fs from "node:fs";
import path from "node:path";

const CAP = 10;
const root = process.cwd();
const check = process.argv.includes("--check");

function loadCourse(dir) {
  const src = fs.readFileSync(path.join(root, "courses", dir, "course.js"), "utf8");
  const window = {};
  new Function("window", src)(window);
  return window.COURSE;
}

// pull each .quiz block's answer index, why, question text, and button labels
function harvest(html) {
  const out = [];
  const block = /<div class="quiz"([^>]*)>([\s\S]*?)<\/div>/g;
  let m;
  while ((m = block.exec(html))) {
    const attrs = m[1], body = m[2];
    const a = attrs.match(/data-answer="(\d+)"/);
    const why = attrs.match(/data-why="([^"]*)"/);
    const q = body.match(/<p class="q">([\s\S]*?)<\/p>/);
    const opts = [...body.matchAll(/<button>([\s\S]*?)<\/button>/g)].map((b) => b[1].trim());
    if (!a || !q || opts.length < 2) continue;
    out.push({ q: q[1].trim(), opts, a: +a[1], why: why ? why[1] : "" });
  }
  return out;
}

function buildCourse(dir) {
  const course = loadCourse(dir);
  const byModule = {};
  for (const l of course.lessons) {
    const file = path.join(root, "courses", dir, "lessons", l.slug + ".html");
    for (const item of harvest(fs.readFileSync(file, "utf8"))) {
      (byModule[l.module] ||= []).push({ ...item, lesson: l.slug, n: l.n, title: l.title });
    }
  }
  for (const mid of Object.keys(byModule)) byModule[mid] = byModule[mid].slice(0, CAP);
  return byModule;
}

function validate(dir, data) {
  const errs = [];
  const mids = new Set(loadCourse(dir).modules.map((m) => m.id));
  for (const mid of mids) if (!data[mid] || !data[mid].length) errs.push(`${dir}/${mid}: no questions`);
  for (const [mid, qs] of Object.entries(data))
    qs.forEach((x, i) => {
      if (!(x.a >= 0 && x.a < x.opts.length)) errs.push(`${dir}/${mid}[${i}]: answer ${x.a} out of range`);
    });
  return errs;
}

const dirs = fs.readdirSync(path.join(root, "courses"));
let failed = false;
for (const dir of dirs) {
  const data = buildCourse(dir);
  const errs = validate(dir, data);
  const counts = Object.entries(data).map(([k, v]) => `${k}:${v.length}`).join(" ");
  if (errs.length) { failed = true; console.error(`✗ ${dir} — ${errs.join("; ")}`); continue; }
  if (!check) {
    const out = "/* GENERATED by tools/quiz-data.mjs — do not edit. Re-run after editing lesson quizzes. */\n" +
      "window.QUIZ = " + JSON.stringify(data, null, 1) + ";\n";
    fs.writeFileSync(path.join(root, "courses", dir, "quiz-data.js"), out);
  }
  console.log(`${check ? "✓ (check) " : "✓ wrote "}${dir}/quiz-data.js — ${counts}`);
}
if (failed) process.exit(1);
