/* quiz-data.mjs — per-course generators harvested from the lesson HTML.
   Run from the repo root:  node tools/quiz-data.mjs   (add --check to validate only).
   Writes two files per course, re-run after editing lessons:
   1. courses/<course>/quiz-data.js = window.QUIZ = { m1:[…], … } — the scored
      end-of-module quizzes, harvested from each lesson's inline .quiz blocks
      (<div class="quiz" data-answer data-why>…<p class="q">…</p><button>…</button>…</div>),
      grouped by the lesson's module and capped at 10 questions each.
   2. courses/<course>/search-index.js = window.SEARCH_INDEX = [{slug,n,title,blurb,headings}]
      — title/blurb from course.js plus each lesson's h2 headings, for assets/search.js.
   Idempotent, no deps. */
import fs from "node:fs";
import path from "node:path";

const CAP = 10;
const root = process.cwd();
const check = process.argv.includes("--check");

function loadCourse(dir) {
  const src = fs.readFileSync(path.join(root, "courses", dir, "course.js"), "utf8");
  const window = {};
  new Function("window", src)(window);
  return window.COURSE;
}

// pull each .quiz block's answer index, why, question text, and button labels
function harvest(html) {
  const out = [];
  const block = /<div class="quiz"([^>]*)>([\s\S]*?)<\/div>/g;
  let m;
  while ((m = block.exec(html))) {
    const attrs = m[1], body = m[2];
    const a = attrs.match(/data-answer="(\d+)"/);
    const why = attrs.match(/data-why="([^"]*)"/);
    const q = body.match(/<p class="q">([\s\S]*?)<\/p>/);
    const opts = [...body.matchAll(/<button>([\s\S]*?)<\/button>/g)].map((b) => b[1].trim());
    if (!a || !q || opts.length < 2) continue;
    out.push({ q: q[1].trim(), opts, a: +a[1], why: why ? why[1] : "" });
  }
  return out;
}

// visible h2 section headings (drop tags/entities/whitespace), skip the generic ones
const SKIP_HEAD = new Set(["check yourself"]);
function headings(html) {
  return [...html.matchAll(/<h2[^>]*>([\s\S]*?)<\/h2>/g)]
    .map((m) => m[1].replace(/<[^>]+>/g, "").replace(/&[^;]+;/g, " ").replace(/\s+/g, " ").trim())
    .filter((t) => t && !SKIP_HEAD.has(t.toLowerCase()));
}

function buildCourse(dir) {
  const course = loadCourse(dir);
  const byModule = {}, index = [];
  for (const l of course.lessons) {
    const file = path.join(root, "courses", dir, "lessons", l.slug + ".html");
    const html = fs.readFileSync(file, "utf8");
    for (const item of harvest(html))
      (byModule[l.module] ||= []).push({ ...item, lesson: l.slug, n: l.n, title: l.title });
    index.push({ slug: l.slug, n: l.n, title: l.title, blurb: l.blurb, headings: headings(html) });
  }
  for (const mid of Object.keys(byModule)) byModule[mid] = byModule[mid].slice(0, CAP);
  return { byModule, index };
}

function validate(dir, data) {
  const errs = [];
  const mids = new Set(loadCourse(dir).modules.map((m) => m.id));
  for (const mid of mids) if (!data[mid] || !data[mid].length) errs.push(`${dir}/${mid}: no questions`);
  for (const [mid, qs] of Object.entries(data))
    qs.forEach((x, i) => {
      if (!(x.a >= 0 && x.a < x.opts.length)) errs.push(`${dir}/${mid}[${i}]: answer ${x.a} out of range`);
    });
  return errs;
}

const dirs = fs.readdirSync(path.join(root, "courses"));
let failed = false;
const banner = "/* GENERATED by tools/quiz-data.mjs — do not edit. Re-run after editing lessons. */\n";
for (const dir of dirs) {
  const { byModule, index } = buildCourse(dir);
  const errs = validate(dir, byModule);
  const counts = Object.entries(byModule).map(([k, v]) => `${k}:${v.length}`).join(" ");
  if (errs.length) { failed = true; console.error(`✗ ${dir} — ${errs.join("; ")}`); continue; }
  if (!check) {
    fs.writeFileSync(path.join(root, "courses", dir, "quiz-data.js"),
      banner + "window.QUIZ = " + JSON.stringify(byModule, null, 1) + ";\n");
    fs.writeFileSync(path.join(root, "courses", dir, "search-index.js"),
      banner + "window.SEARCH_INDEX = " + JSON.stringify(index) + ";\n");
  }
  console.log(`${check ? "✓ (check) " : "✓ wrote "}${dir} — quiz [${counts}], search index ${index.length} lessons`);
}
if (failed) process.exit(1);
